export const DEMO_CHALLENGES = [
  {
    _id: 'demo-1',
    title: 'Rural Healthcare Access in Palamu',
    description: 'Remote villages lack primary healthcare facilities within 10km radius, causing delayed treatment for common ailments.',
    category: 'Healthcare',
    district: 'Palamu',
    status: 'validated',
    priority: 'Critical',
    priorityScore: 92,
    location: { lat: 23.85, lng: 84.1, address: 'Palamu District, Jharkhand' },
    submittedBy: { name: 'Ramesh Kumar' },
    createdAt: '2025-11-15T10:00:00Z',
    affectedPopulation: 15000,
    upvotes: 234,
  },
  {
    _id: 'demo-2',
    title: 'Water Scarcity in Ranchi Slums',
    description: 'Irregular water supply affects 5,000 households during summer months with only 2 hours of supply per day.',
    category: 'Water',
    district: 'Ranchi',
    status: 'in_review',
    priority: 'High',
    priorityScore: 78,
    location: { lat: 23.3441, lng: 85.3096, address: 'Kanke Road, Ranchi' },
    submittedBy: { name: 'Sunita Devi' },
    createdAt: '2025-12-01T08:30:00Z',
    affectedPopulation: 5000,
    upvotes: 156,
  },
  {
    _id: 'demo-3',
    title: 'Digital Literacy for Tribal Youth',
    description: 'Youth in Gumla district need access to digital skills training and internet connectivity for employment opportunities.',
    category: 'Education',
    district: 'Gumla',
    status: 'matched',
    priority: 'Medium',
    priorityScore: 65,
    location: { lat: 23.04, lng: 84.54, address: 'Gumla Town' },
    submittedBy: { name: 'Anil Munda' },
    createdAt: '2025-10-20T14:00:00Z',
    affectedPopulation: 3000,
    upvotes: 89,
  },
  {
    _id: 'demo-4',
    title: 'Waste Management in Jamshedpur',
    description: 'Industrial and municipal waste accumulation in residential areas causing health hazards and environmental damage.',
    category: 'Environment',
    district: 'East Singhbhum',
    status: 'project_active',
    priority: 'High',
    priorityScore: 81,
    location: { lat: 22.8046, lng: 86.2029, address: 'Sakchi, Jamshedpur' },
    submittedBy: { name: 'Priya Sharma' },
    createdAt: '2025-09-05T11:00:00Z',
    affectedPopulation: 25000,
    upvotes: 312,
  },
];

export const DEMO_PROJECTS = [
  {
    _id: 'proj-1',
    title: 'Telemedicine Kiosk Network',
    challenge: { _id: 'demo-1', title: 'Rural Healthcare Access in Palamu' },
    university: { name: 'BIT Mesra' },
    industry: { name: 'Tata Steel CSR' },
    status: 'pilot',
    phase: 'Pilot Deployment',
    progress: 65,
    district: 'Palamu',
    startDate: '2025-08-01',
    teamSize: 12,
    impactMetrics: { beneficiaries: 3200, villages: 8 },
  },
  {
    _id: 'proj-2',
    title: 'Smart Water Monitoring System',
    challenge: { _id: 'demo-2', title: 'Water Scarcity in Ranchi Slums' },
    university: { name: 'Ranchi University' },
    industry: { name: 'JUSCO' },
    status: 'active',
    phase: 'Prototype',
    progress: 40,
    district: 'Ranchi',
    startDate: '2025-10-15',
    teamSize: 8,
    impactMetrics: { beneficiaries: 1200, households: 450 },
  },
  {
    _id: 'proj-3',
    title: 'Tribal Digital Learning Centers',
    challenge: { _id: 'demo-3', title: 'Digital Literacy for Tribal Youth' },
    university: { name: 'XLRI Jamshedpur' },
    status: 'completed',
    phase: 'Impact Assessment',
    progress: 100,
    district: 'Gumla',
    startDate: '2025-03-01',
    teamSize: 15,
    impactMetrics: { beneficiaries: 850, youthTrained: 320 },
  },
];

export const DEMO_UNIVERSITIES = [
  { _id: 'uni-1', name: 'BIT Mesra', location: 'Ranchi', type: 'Technical', activeProjects: 4, students: 8500, specializations: ['Engineering', 'Healthcare Tech', 'Agriculture'] },
  { _id: 'uni-2', name: 'Ranchi University', location: 'Ranchi', type: 'State University', activeProjects: 3, students: 12000, specializations: ['Social Sciences', 'Water Management', 'Education'] },
  { _id: 'uni-3', name: 'XLRI Jamshedpur', location: 'Jamshedpur', type: 'Management', activeProjects: 2, students: 1200, specializations: ['Rural Development', 'CSR', 'Social Enterprise'] },
  { _id: 'uni-4', name: 'NIT Jamshedpur', location: 'Jamshedpur', type: 'Technical', activeProjects: 3, students: 5000, specializations: ['IoT', 'Renewable Energy', 'Manufacturing'] },
  { _id: 'uni-5', name: 'Vinoba Bhave University', location: 'Hazaribagh', type: 'State University', activeProjects: 2, students: 6000, specializations: ['Agriculture', 'Environment', 'Rural Studies'] },
];

export const DEMO_INDUSTRY = [
  { _id: 'ind-1', name: 'Tata Steel CSR', sector: 'Steel & Mining', location: 'Jamshedpur', activeProjects: 5, contribution: 'Funding & Mentorship', focus: ['Healthcare', 'Education', 'Livelihood'] },
  { _id: 'ind-2', name: 'JUSCO', sector: 'Utilities', location: 'Jamshedpur', activeProjects: 3, contribution: 'Infrastructure & Technology', focus: ['Water', 'Sanitation', 'Urban Development'] },
  { _id: 'ind-3', name: 'Usha Martin', sector: 'Manufacturing', location: 'Ranchi', activeProjects: 2, contribution: 'Technology & Skilling', focus: ['Employment', 'Rural Livelihood'] },
  { _id: 'ind-4', name: 'Central Coalfields Ltd', sector: 'Mining', location: 'Ranchi', activeProjects: 2, contribution: 'CSR Funding', focus: ['Environment', 'Healthcare', 'Education'] },
];

export const DEMO_IMPACT = {
  totalBeneficiaries: 52000,
  villagesReached: 145,
  projectsCompleted: 8,
  activeProjects: 12,
  challengesResolved: 18,
  districtsCovered: 18,
  categoryBreakdown: [
    { category: 'Healthcare', count: 5, beneficiaries: 18000 },
    { category: 'Education', count: 4, beneficiaries: 12000 },
    { category: 'Water', count: 3, beneficiaries: 8000 },
    { category: 'Agriculture', count: 3, beneficiaries: 7000 },
    { category: 'Environment', count: 2, beneficiaries: 5000 },
    { category: 'Other', count: 1, beneficiaries: 2000 },
  ],
  monthlyProgress: [
    { month: 'Jan', beneficiaries: 3200, projects: 2 },
    { month: 'Feb', beneficiaries: 4100, projects: 3 },
    { month: 'Mar', beneficiaries: 5800, projects: 4 },
    { month: 'Apr', beneficiaries: 6200, projects: 5 },
    { month: 'May', beneficiaries: 7500, projects: 6 },
    { month: 'Jun', beneficiaries: 8900, projects: 7 },
  ],
};

export const DEMO_GOVERNMENT_STATS = {
  totalChallenges: 24,
  pendingReview: 6,
  validated: 12,
  matched: 8,
  activeProjects: 12,
  completedProjects: 8,
  byDistrict: [
    { district: 'Ranchi', challenges: 8, projects: 4 },
    { district: 'East Singhbhum', challenges: 5, projects: 3 },
    { district: 'Palamu', challenges: 4, projects: 2 },
    { district: 'Gumla', challenges: 3, projects: 2 },
    { district: 'Dhanbad', challenges: 2, projects: 1 },
    { district: 'Bokaro', challenges: 2, projects: 0 },
  ],
  byStatus: [
    { status: 'Submitted', count: 4 },
    { status: 'In Review', count: 6 },
    { status: 'Validated', count: 6 },
    { status: 'Matched', count: 4 },
    { status: 'Project Active', count: 4 },
  ],
  byCategory: [
    { category: 'Healthcare', count: 6 },
    { category: 'Education', count: 5 },
    { category: 'Water', count: 4 },
    { category: 'Agriculture', count: 3 },
    { category: 'Environment', count: 3 },
    { category: 'Other', count: 3 },
  ],
};

export const DEMO_NOTIFICATIONS = [
  { _id: 'n1', message: 'Your challenge "Water Scarcity in Ranchi Slums" is under review', read: false, createdAt: '2025-12-10T09:00:00Z' },
  { _id: 'n2', message: 'New project update: Telemedicine Kiosk Network reached 65% progress', read: true, createdAt: '2025-12-08T14:30:00Z' },
  { _id: 'n3', message: 'Challenge validated: Digital Literacy for Tribal Youth', read: true, createdAt: '2025-12-05T11:00:00Z' },
];

export const DEMO_ADMIN_STATS = {
  totalUsers: 342,
  usersByRole: [
    { role: 'Citizen', count: 245 },
    { role: 'University', count: 28 },
    { role: 'Government', count: 12 },
    { role: 'Industry', count: 18 },
    { role: 'Admin', count: 3 },
  ],
  totalChallenges: 24,
  totalProjects: 20,
  recentActivity: [
    { action: 'User registered', user: 'Amit Singh', time: '2 hours ago' },
    { action: 'Challenge submitted', user: 'Sunita Devi', time: '5 hours ago' },
    { action: 'Project milestone', user: 'BIT Mesra', time: '1 day ago' },
    { action: 'Challenge validated', user: 'Gov. Official', time: '2 days ago' },
  ],
};

export const DEMO_TIMELINE = [
  { date: '2025-11-15', title: 'Challenge Submitted', description: 'Citizen reported the issue with location and evidence.' },
  { date: '2025-11-18', title: 'AI Analysis Complete', description: 'Categorized as Healthcare, priority score 92.' },
  { date: '2025-11-22', title: 'Government Validation', description: 'Validated by District Health Officer.' },
  { date: '2025-12-01', title: 'University Matched', description: 'BIT Mesra accepted the challenge for research.' },
  { date: '2025-12-10', title: 'Project Initiated', description: 'Telemedicine Kiosk Network project started.' },
];
